language: php
php:
  - "7.2"

addons:
  chrome: stable

install:
  - composer install --prefer-dist
  - composer require --dev symfony/framework-bundle

script:
  - composer cs
  - composer static-analysis
  - composer remove --dev symfony/framework-bundle
  - composer test

cache:
  directories:
    - $HOME/.composer/cache/files
